<?php
return array (
  'iparl_webhook_key' => array(
    'group_name' => 'iParl Integration Settings',
    'group' => 'iparl',
    'name' => 'iparl_webhook_key',
    'type' => 'String',
    'title' => 'iParl webhook secret',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' =>  'Secret Key that iParl passes with webhook data.',
    'help_text' => 'iParl will provide this when you set up the POST Data API.',
  ),
  'iparl_user_name' => array(
    'group_name' => 'iParl Integration Settings',
    'group' => 'iparl',
    'name' => 'iparl_user_name',
    'type' => 'String',
    'title' => 'iParl username (not your email)',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' =>  'This will be a one-word code that is assigned to your account.',
    'help_text' => 'You can find this by logging in to iParl, going to Help » Info API Help, then look at any of the URLs that look like http://www.iparl.com/api/foobar/actions - in this example foobar would be your username.',
  ),
  'iparl_logging' => array(
    'group_name' => 'iParl Integration Settings',
    'group' => 'iparl',
    'name' => 'iparl_logging',
    'type' => 'Integer', // Boolean is valid, but Mailing.settings.php uses Integer for checkbox so I did too.
    'default' => 0,
    'title' => 'Debug logging',
    'html_type' => 'select',
    'quick_form_type' => 'Element',
    'add' => '4.6',
    'is_domain' => '1',
    'is_contact' => 0,
    'html_attributes' => Array(
      '0' => 'No logging',
      '1' => 'Log all iParl webhook calls.',
    ),
    'description' =>  'Logs all calls by the iParl webhook.',
    'help_text' => 'Advisable until you are sure all is working well.',
  ),
  /*
  'iparl_logging' => array(
    'group_name' => 'iParl Integration Settings',
    'group' => 'iparl',
    'name' => 'iparl_logging',
    'type' => 'Integer', // Boolean is valid, but Mailing.settings.php uses Integer for checkbox so I did too.
    'default' => 0,
    'title' => 'Debug logging',
    //'html_type' => 'checkbox',
    'quick_form_type' => 'Checkbox',
    'add' => '4.6',
    'is_domain' => '1',
    'is_contact' => 0,
    'description' =>  'Logs all calls by the iParl webhook.',
    'help_text' => 'Advisable until you are sure all is working well.',
  ),
   */
);
